### ISSUE TITLE
Add correct attributions to README

### ISSUE THREAD

**Issue by Galadirith** [talkol/spiderman#2]
@talkol You've created amazing work here, it's a really fun experience 😊

I found that you have used several assets in your WebXR app that are created by others, some you provide incomplete credits for in your [`README.md`](https://github.com/talkol/spiderman/blob/master/README.md#credits) others you don't credit. A couple that I noticed were the ["Crystal Kyber"](https://sketchfab.com/3d-models/crystal-kyber-1d769339a8cc45fda2ba6b31ce91160f) by [Ian Diaz](https://sketchfab.com/Dyckzu) which seems to be used mostly unmodified and incompletely credited and ["Spider-Man:Interactive View"](https://sketchfab.com/3d-models/spider-maninteractive-view-74decbbcc4aa4665908d21ba157b8dda) by [Pawas Saxena](https://sketchfab.com/pawastastic) where you have cropped most of the model out to leave only the hands and added your own hand animations (did you create the animations yourself?) which you haven't credited.

I would like to suggest changes for the credits for these two sets of Creative Commons assets ([_Frequently Asked Questions_](https://creativecommons.org/faq/#how-do-i-properly-attribute-material-offered-under-a-creative-commons-license), [_Best practices for attribution_](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution))

> ["Crystal Kyber"](https://sketchfab.com/3d-models/crystal-kyber-1d769339a8cc45fda2ba6b31ce91160f) by [Ian Diaz](https://sketchfab.com/Dyckzu) licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) / Source assets are compressed

> `leftHand.glb` and `rightHand.glb` are a derivative of ["Spider-Man:Interactive View"](https://sketchfab.com/3d-models/spider-maninteractive-view-74decbbcc4aa4665908d21ba157b8dda) by [Pawas Saxena](https://sketchfab.com/pawastastic) licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

You have also copied in several pieces of source code from [A-Frame](https://github.com/aframevr/aframe), for example [`hand.js`](https://github.com/talkol/spiderman/blob/master/hand.js) is mostly the same as [`hand-controls.js`](https://github.com/aframevr/aframe/blob/master/src/components/hand-controls.js). A candidate credit could be

> This repository incorporates code from [`aframe`](https://github.com/aframevr/aframe) which is release under the [MIT license](https://github.com/aframevr/aframe/blob/master/LICENSE).

and ideally you would also include A-Frames [`LICENSE`](https://github.com/aframevr/aframe/blob/master/LICENSE) in your repo since you do use large blocks of code. You could add the copyright notice from [`LICENSE`](https://github.com/aframevr/aframe/blob/master/LICENSE) to the beginning of any source files that are majority code from [`aframe`](https://github.com/aframevr/aframe) or just include it in your [`LICENSE.md`](https://github.com/talkol/spiderman/blob/master/LICENSE.md).

The license of the assets that you've used that are created by others that I've found _require_ you to add proper attribution. I completely appreciate that writing full attributions is tedious, and I know there is certainly no bad intent on your part since you have tried to give attribution. But regardless of what is required, it would be very thoughtful and respectful to recognise and fully attribute the awesome work by others that has gone in to creating your amazing experience 😊

I would also suggest adding complete attributions for the other assets you have used that are created by others.

**Comment by talkol** [comment]
lol, thanks! I'll add your suggestions, thanks for taking the time to get all the correct ones!

**Comment by talkol** [comment]
I'm awestruck by how you found all of those, that's some world class reverse engineering.. you nailed all the assets by third parties

**Comment by Galadirith** [comment]
@talkol Thank you so much for adding those attributions so quickly, I really appreciate it. I only really noticed them because I was digging around in your source code so much. I really love the experience and I wanted to understand more about how you did it. Not everyone shares their source code so I am really really grateful 😊

The bit I really wanted to learn about was your movement mechanics. I usually get motion sickness when I don't use teleport controls, but for some reason in your Spiderman experience my motion sickness almost disappeared. I can even jump over buildings without too much issue.

![highrise](https://user-images.githubusercontent.com/1201875/71860138-a3181880-30e9-11ea-9fdf-4254130944d9.gif)

I think this might have something to do with your [smooth controls you mentioned](https://twitter.com/koltal/status/1214164010410663936). I definitely want to study your code more to understand your implementation. Whatever the reason is I'm just so glad I get to experience this without any real motion sickness 😊
